---
version: 0.0.31
slug: wired_device_can
name: WiredDevice CAN
description: This enables CAN interfaces on HassOS
url: https://wiredsquare.com
arch:
  - armhf
  - armv7
  - aarch64
host_network: true
options:
  - bitrate: 50000
  - restart-ms: 100
  - tx_queue_length: 1000
schema:
  - bitrate: str
  - restart-ms: str
  - tx_queue_length: str
startup: system
init: false
map:
  - config:rw
boot: auto
apparmor: false
ingress: false
stage: experimental
privileged:
   - NET_ADMIN
full_access: true
